# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cclogs < Formula
  desc "Claude Code Log Shipper - backup session logs to S3-compatible storage"
  homepage "https://github.com/13rac1/cclogs"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/13rac1/cclogs/releases/download/v1.0.0/cclogs_1.0.0_darwin_amd64.tar.gz"
      sha256 "a2ce8596436c8d150d108c84a699c83be715c91e5b9553fb6e1d6cd59b67d25a"

      def install
        bin.install "cclogs"
      end
    end
    on_arm do
      url "https://github.com/13rac1/cclogs/releases/download/v1.0.0/cclogs_1.0.0_darwin_arm64.tar.gz"
      sha256 "bc1123e072d21d99733d66cde0c61bdee01c55a1cf6fd2278d4cc28f9281cc01"

      def install
        bin.install "cclogs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/13rac1/cclogs/releases/download/v1.0.0/cclogs_1.0.0_linux_amd64.tar.gz"
        sha256 "0243012d2ba84b6855b36c44b077d9fb7c6cda97da7b1633198c5e3ccf467b25"

        def install
          bin.install "cclogs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/13rac1/cclogs/releases/download/v1.0.0/cclogs_1.0.0_linux_arm64.tar.gz"
        sha256 "614b2a702ed152129e5f424299d0a3fb4eae5c7cac7e1046f5401f6a404b2f31"

        def install
          bin.install "cclogs"
        end
      end
    end
  end

  test do
    system "#{bin}/cclogs", "--version"
  end
end
